/**********************************************************************************************
 * This class was automatically generated by Adichatz tools on Mon Jul 06 18:32:42 CEST 2020
 *
 * 				+----------------------------------------+
 * 				| BE CAREFUL BEFORE UPDATING THIS CLASS! |
 * 				+----------------------------------------+
 *
 * Changes will be transient up to next generation process.
 * **********************************************************************************************/
package org.adichatz.studio.gencode.model;

import org.adichatz.engine.extra.AdiResourceURI;
import org.adichatz.engine.model.AEntityMetaModel;
import org.adichatz.engine.model.PropertyField;
import org.adichatz.engine.model.RefField;
import org.adichatz.engine.plugin.PluginEntity;
import org.adichatz.generator.xjc.ArgTabFolderType;
import org.adichatz.studio.xjc.scenario.AXjcEntityMetaModel;

@AdiResourceURI(URI="adi://org.adichatz.studio/model/ArgTabFolderMM")
public class ArgTabFolderMM extends AXjcEntityMetaModel<ArgTabFolderType> {
	/**
	 * Creates the MetaModel class for ArgTabFolderMM.
	 *
	 */
	public ArgTabFolderMM(PluginEntity<?> pluginEntity) {
		super(pluginEntity);
		pluginEntity.setSuperEntityURI("adi://org.adichatz.studio/model/FieldContainerMM");
		create();
	}

	/**
	 * Create contents for MetaModel ArgTabFolderMM.
	 */
	public void create(){
		
		/**
		 *  add a join column (ManyToOne) for field labelProvider
		 */
		RefField<?> refField;
		refField = new RefField(this, "labelProvider", null, "adi://org.adichatz.studio/model/LabelProviderMM");
		
		/**
		 *  add a property field for field initValues
		 */
		new PropertyField(this, "initValues");
		
		/**
		 *  add a property field for field selection
		 */
		new PropertyField(this, "selection");
		
		/**
		 *  add a property field for field displayedValues
		 */
		new PropertyField(this, "displayedValues");
		
		/**
		 *  add a property field for field values
		 */
		new PropertyField(this, "values");
		
		/**
		 *  add a property field for field labelProviderClassName
		 */
		new PropertyField(this, "labelProviderClassName");
		addSuperFields();
	}
	
	/* (non-Javadoc)
	 * @see org.adichatz.engine.model.AEntityMetaModel#getBeanClass()
	 */
	@Override
	public Class<ArgTabFolderType> getBeanClass() {
		return ArgTabFolderType.class;
	}
	@Override
	protected void addSuperFields(){
		AEntityMetaModel<?> superEntityMM = pluginEntity.getPluginEntityTree().getEntityMM("adi://org.adichatz.studio/model/FieldContainerMM");
		fieldMap.putAll(superEntityMM.getFieldMap());
		super.addSuperFields();
	}
}