/**********************************************************************************************
 * This class was automatically generated by Adichatz tools on Sat Dec 07 15:16:05 CET 2019
 *
 * 				+----------------------------------------+
 * 				| BE CAREFUL BEFORE UPDATING THIS CLASS! |
 * 				+----------------------------------------+
 *
 * Changes will be transient up to next generation process.
 * **********************************************************************************************/
package org.adichatz.studio.gencode.model;

import org.adichatz.engine.extra.AdiResourceURI;
import org.adichatz.engine.model.AEntityMetaModel;
import org.adichatz.engine.plugin.PluginEntity;
import org.adichatz.generator.xjc.CompositeBagType;
import org.adichatz.studio.xjc.scenario.AXjcEntityMetaModel;
import org.adichatz.studio.xjc.scenario.XjcEntitySet;

@AdiResourceURI(URI="adi://org.adichatz.studio/model/CompositeBagMM")
public class CompositeBagMM extends AXjcEntityMetaModel<CompositeBagType> {
	/**
	 * Creates the MetaModel class for CompositeBagMM.
	 *
	 */
	public CompositeBagMM(PluginEntity<?> pluginEntity) {
		super(pluginEntity);
		pluginEntity.setSuperEntityURI("adi://org.adichatz.studio/model/CollectionMM");
		create();
	}

	/**
	 * Create contents for MetaModel CompositeBagMM.
	 */
	public void create(){
		
		// add one to many for field 'scrolledFormOrSectionOrComposite' (parent clause='null')
		XjcEntitySet oneToMany;
		oneToMany = new XjcEntitySet(this, "scrolledFormOrSectionOrComposite", null);
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/ScrolledFormMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/SectionMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/CompositeMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/GroupMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/PGroupMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/SashFormMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/ScrolledCompositeMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/CTabFolderMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/ArgTabFolderMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/PShelfMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/ArgPShelfMM");
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/IncludeMM");
		addSuperFields();
	}
	
	/* (non-Javadoc)
	 * @see org.adichatz.engine.model.AEntityMetaModel#getBeanClass()
	 */
	@Override
	public Class<CompositeBagType> getBeanClass() {
		return CompositeBagType.class;
	}
	@Override
	protected void addSuperFields(){
		AEntityMetaModel<?> superEntityMM = pluginEntity.getPluginEntityTree().getEntityMM("adi://org.adichatz.studio/model/CollectionMM");
		fieldMap.putAll(superEntityMM.getFieldMap());
		super.addSuperFields();
	}
}