/**********************************************************************************************
 * This class was automatically generated by Adichatz tools on Mon Jul 06 18:32:51 CEST 2020
 *
 * 				+----------------------------------------+
 * 				| BE CAREFUL BEFORE UPDATING THIS CLASS! |
 * 				+----------------------------------------+
 *
 * Changes will be transient up to next generation process.
 * **********************************************************************************************/
package org.adichatz.studio.gencode.model;

import org.adichatz.engine.extra.AdiResourceURI;
import org.adichatz.engine.model.AEntityMetaModel;
import org.adichatz.engine.model.PropertyField;
import org.adichatz.engine.plugin.PluginEntity;
import org.adichatz.generator.xjc.CopyResourceType;
import org.adichatz.studio.xjc.scenario.AXjcEntityMetaModel;
import org.adichatz.studio.xjc.scenario.XjcEntitySet;

@AdiResourceURI(URI="adi://org.adichatz.studio/model/CopyResourceMM")
public class CopyResourceMM extends AXjcEntityMetaModel<CopyResourceType> {
	/**
	 * Creates the MetaModel class for CopyResourceMM.
	 *
	 */
	public CopyResourceMM(PluginEntity<?> pluginEntity) {
		super(pluginEntity);
		pluginEntity.setSuperEntityURI("adi://org.adichatz.studio/model/RemoveResourceMM");
		create();
	}

	/**
	 * Create contents for MetaModel CopyResourceMM.
	 */
	public void create(){
		
		/**
		 *  add a property field for field sourceURI
		 */
		new PropertyField(this, "sourceURI");
		
		/**
		 *  add a property field for field force
		 */
		new PropertyField(this, "force");
		
		// add one to many for field 'replacement' (parent clause='null')
		XjcEntitySet oneToMany;
		oneToMany = new XjcEntitySet(this, "replacement", null);
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/ReplacementMM");
		addSuperFields();
	}
	
	/* (non-Javadoc)
	 * @see org.adichatz.engine.model.AEntityMetaModel#getBeanClass()
	 */
	@Override
	public Class<CopyResourceType> getBeanClass() {
		return CopyResourceType.class;
	}
	@Override
	protected void addSuperFields(){
		AEntityMetaModel<?> superEntityMM = pluginEntity.getPluginEntityTree().getEntityMM("adi://org.adichatz.studio/model/RemoveResourceMM");
		fieldMap.putAll(superEntityMM.getFieldMap());
		super.addSuperFields();
	}
}