/**********************************************************************************************
 * This class was automatically generated by Adichatz tools on Mon Jul 06 18:32:25 CEST 2020
 *
 * 				+----------------------------------------+
 * 				| BE CAREFUL BEFORE UPDATING THIS CLASS! |
 * 				+----------------------------------------+
 *
 * Changes will be transient up to next generation process.
 * **********************************************************************************************/
package org.adichatz.studio.gencode.model;

import org.adichatz.engine.extra.AdiResourceURI;
import org.adichatz.engine.plugin.PluginEntity;
import org.adichatz.generator.xjc.CrossReferencesType;
import org.adichatz.studio.xjc.scenario.AXjcEntityMetaModel;
import org.adichatz.studio.xjc.scenario.XjcEntitySet;

@AdiResourceURI(URI="adi://org.adichatz.studio/model/CrossReferencesMM")
public class CrossReferencesMM extends AXjcEntityMetaModel<CrossReferencesType> {
	/**
	 * Creates the MetaModel class for CrossReferencesMM.
	 *
	 */
	public CrossReferencesMM(PluginEntity<?> pluginEntity) {
		super(pluginEntity);
		create();
	}

	/**
	 * Create contents for MetaModel CrossReferencesMM.
	 */
	public void create(){
		
		// add one to many for field 'crossReference' (parent clause='null')
		XjcEntitySet oneToMany;
		oneToMany = new XjcEntitySet(this, "crossReference", null);
		oneToMany.addElementEntity("adi://org.adichatz.studio/model/CrossReferenceMM");
	}
	
	/* (non-Javadoc)
	 * @see org.adichatz.engine.model.AEntityMetaModel#getBeanClass()
	 */
	@Override
	public Class<CrossReferencesType> getBeanClass() {
		return CrossReferencesType.class;
	}
}