/**********************************************************************************************
 * This class was automatically generated by Adichatz tools on Sat Dec 07 15:15:36 CET 2019
 *
 * 				+----------------------------------------+
 * 				| BE CAREFUL BEFORE UPDATING THIS CLASS! |
 * 				+----------------------------------------+
 *
 * Changes will be transient up to next generation process.
 * **********************************************************************************************/
package org.adichatz.studio.gencode.model;

import org.adichatz.engine.extra.AdiResourceURI;
import org.adichatz.engine.model.PropertyField;
import org.adichatz.engine.plugin.PluginEntity;
import org.adichatz.generator.xjc.ElementType;
import org.adichatz.studio.xjc.scenario.AXjcEntityMetaModel;

@AdiResourceURI(URI="adi://org.adichatz.studio/model/ElementMM")
public class ElementMM extends AXjcEntityMetaModel<ElementType> {
	/**
	 * Creates the MetaModel class for ElementMM.
	 *
	 */
	public ElementMM(PluginEntity<?> pluginEntity) {
		super(pluginEntity);
		create();
	}

	/**
	 * Create contents for MetaModel ElementMM.
	 */
	public void create(){
		
		/**
		 *  add a property field for field id
		 */
		new PropertyField(this, "id");
		
		/**
		 *  add a property field for field parentIndex
		 */
		new PropertyField(this, "parentIndex");
	}
	
	/* (non-Javadoc)
	 * @see org.adichatz.engine.model.AEntityMetaModel#getBeanClass()
	 */
	@Override
	public Class<ElementType> getBeanClass() {
		return ElementType.class;
	}
}