/**********************************************************************************************
 * This class was automatically generated by Adichatz tools on Mon Jul 06 18:33:04 CEST 2020
 *
 * 				+----------------------------------------+
 * 				| BE CAREFUL BEFORE UPDATING THIS CLASS! |
 * 				+----------------------------------------+
 *
 * Changes will be transient up to next generation process.
 * **********************************************************************************************/
package org.adichatz.studio.gencode.model;

import org.adichatz.engine.extra.AdiResourceURI;
import org.adichatz.engine.model.AEntityMetaModel;
import org.adichatz.engine.model.PropertyField;
import org.adichatz.engine.plugin.PluginEntity;
import org.adichatz.generator.xjc.NativeContentProviderType;
import org.adichatz.studio.xjc.scenario.AXjcEntityMetaModel;

@AdiResourceURI(URI="adi://org.adichatz.studio/model/NativeContentProviderMM")
public class NativeContentProviderMM extends AXjcEntityMetaModel<NativeContentProviderType> {
	/**
	 * Creates the MetaModel class for NativeContentProviderMM.
	 *
	 */
	public NativeContentProviderMM(PluginEntity<?> pluginEntity) {
		super(pluginEntity);
		pluginEntity.setSuperEntityURI("adi://org.adichatz.studio/model/ContentProviderMM");
		create();
	}

	/**
	 * Create contents for MetaModel NativeContentProviderMM.
	 */
	public void create(){
		
		/**
		 *  add a property field for field fieldName
		 */
		new PropertyField(this, "fieldName");
		addSuperFields();
	}
	
	/* (non-Javadoc)
	 * @see org.adichatz.engine.model.AEntityMetaModel#getBeanClass()
	 */
	@Override
	public Class<NativeContentProviderType> getBeanClass() {
		return NativeContentProviderType.class;
	}
	@Override
	protected void addSuperFields(){
		AEntityMetaModel<?> superEntityMM = pluginEntity.getPluginEntityTree().getEntityMM("adi://org.adichatz.studio/model/ContentProviderMM");
		fieldMap.putAll(superEntityMM.getFieldMap());
		super.addSuperFields();
	}
}