/**********************************************************************************************
 * This class was automatically generated by Adichatz tools on Sat Dec 07 15:15:57 CET 2019
 *
 * 				+----------------------------------------+
 * 				| BE CAREFUL BEFORE UPDATING THIS CLASS! |
 * 				+----------------------------------------+
 *
 * Changes will be transient up to next generation process.
 * **********************************************************************************************/
package org.adichatz.studio.gencode.model;

import org.adichatz.engine.extra.AdiResourceURI;
import org.adichatz.engine.model.AEntityMetaModel;
import org.adichatz.engine.model.PropertyField;
import org.adichatz.engine.model.RefField;
import org.adichatz.engine.plugin.PluginEntity;
import org.adichatz.generator.xjc.RadioGroupType;
import org.adichatz.studio.xjc.scenario.AXjcEntityMetaModel;

@AdiResourceURI(URI="adi://org.adichatz.studio/model/RadioGroupMM")
public class RadioGroupMM extends AXjcEntityMetaModel<RadioGroupType> {
	/**
	 * Creates the MetaModel class for RadioGroupMM.
	 *
	 */
	public RadioGroupMM(PluginEntity<?> pluginEntity) {
		super(pluginEntity);
		pluginEntity.setSuperEntityURI("adi://org.adichatz.studio/model/RefControlMM");
		create();
	}

	/**
	 * Create contents for MetaModel RadioGroupMM.
	 */
	public void create(){
		
		/**
		 *  add a join column (ManyToOne) for field layout
		 */
		RefField<?> refField;
		refField = new RefField(this, "layout", null, "adi://org.adichatz.studio/model/LayoutMM");
		
		/**
		 *  add a property field for field defaultSelection
		 */
		new PropertyField(this, "defaultSelection");
		addSuperFields();
	}
	
	/* (non-Javadoc)
	 * @see org.adichatz.engine.model.AEntityMetaModel#getBeanClass()
	 */
	@Override
	public Class<RadioGroupType> getBeanClass() {
		return RadioGroupType.class;
	}
	@Override
	protected void addSuperFields(){
		AEntityMetaModel<?> superEntityMM = pluginEntity.getPluginEntityTree().getEntityMM("adi://org.adichatz.studio/model/RefControlMM");
		fieldMap.putAll(superEntityMM.getFieldMap());
		super.addSuperFields();
	}
}