/**********************************************************************************************
 * This class was automatically generated by Adichatz tools on Sat Dec 07 15:16:31 CET 2019
 *
 * 				+----------------------------------------+
 * 				| BE CAREFUL BEFORE UPDATING THIS CLASS! |
 * 				+----------------------------------------+
 *
 * Changes will be transient up to next generation process.
 * **********************************************************************************************/
package org.adichatz.studio.gencode.model;

import org.adichatz.engine.extra.AdiResourceURI;
import org.adichatz.engine.model.PropertyField;
import org.adichatz.engine.plugin.PluginEntity;
import org.adichatz.generator.xjc.ReplacementType;
import org.adichatz.studio.xjc.scenario.AXjcEntityMetaModel;

@AdiResourceURI(URI="adi://org.adichatz.studio/model/ReplacementMM")
public class ReplacementMM extends AXjcEntityMetaModel<ReplacementType> {
	/**
	 * Creates the MetaModel class for ReplacementMM.
	 *
	 */
	public ReplacementMM(PluginEntity<?> pluginEntity) {
		super(pluginEntity);
		create();
	}

	/**
	 * Create contents for MetaModel ReplacementMM.
	 */
	public void create(){
		
		/**
		 *  add a property field for field token
		 */
		new PropertyField(this, "token");
		
		/**
		 *  add a property field for field value
		 */
		new PropertyField(this, "value");
	}
	
	/* (non-Javadoc)
	 * @see org.adichatz.engine.model.AEntityMetaModel#getBeanClass()
	 */
	@Override
	public Class<ReplacementType> getBeanClass() {
		return ReplacementType.class;
	}
}