/**********************************************************************************************
 * This class was automatically generated by Adichatz tools on Tue Jul 07 12:30:03 CEST 2020
 *
 * 				+----------------------------------------+
 * 				| BE CAREFUL BEFORE UPDATING THIS CLASS! |
 * 				+----------------------------------------+
 *
 * Changes will be transient up to next generation process.
 * **********************************************************************************************/
package org.adichatz.jpa.gencode.common.toolBar;

import java.util.function.BooleanSupplier;
import org.adichatz.common.ejb.util.IEntityConstants;
import org.adichatz.engine.controller.IContainerController;
import org.adichatz.engine.controller.action.ActionController;
import org.adichatz.engine.controller.collection.ManagedToolBarController;
import org.adichatz.engine.controller.utils.ElementaryAccessibility;
import org.adichatz.engine.core.AIncludeCore;
import org.adichatz.engine.extra.AdiResourceURI;
import org.adichatz.engine.plugin.AdiContext;
import org.adichatz.engine.plugin.ParamMap;
import org.adichatz.jpa.action.DeleteEntityAction;
import org.adichatz.jpa.action.DeleteEntityAndCloseAction;
import org.adichatz.jpa.action.RefreshEntityAction;

@AdiResourceURI(URI="adi://org.adichatz.jpa/common.toolBar/SectionDetailTBM")
public class SectionDetailTBM extends AIncludeCore {
	// the ManagedToolBarController managedToolBarTB.
	protected ManagedToolBarController managedToolBarTB;
	// the ActionController refreshEntityActionACT.
	private ActionController refreshEntityActionACT;
	// the ActionController deleteEntityAndCloseActionACT.
	private ActionController deleteEntityAndCloseActionACT;
	// the ActionController deleteEntityActionACT.
	private ActionController deleteEntityActionACT;
	/**
	 * Instantiates a new SectionDetailTBM.
	 * 
	 * This constructor could be used by Column parameter. (see org.adichatz.jpa)
	 * 
	 * @param parentContext
	 *            the parent context
	 * @param parentController
	 *            the parent controller
	 */
	public SectionDetailTBM(AdiContext parentContext, IContainerController parentController) {
		coreController = parentController;
	}

	/**
	 * Creates the include SectionDetailTBM.
	 *
	 * @param context
	 *            The context of the root controller
	 * @param parent controller
	 *            The collection parentController
	 * @param id
	 *            The include id
	 * @param parentContext
	 *            The parent context
	 */
	public SectionDetailTBM(ParamMap paramMap, IContainerController parentController, String id, AdiContext parentContext) {
		super(paramMap, parentController, id, parentContext);
		coreController = parentController;
	}

	/**
	 * creates contents
	 */
	public void createContents(){
		// Creates control for ManagedToolBarController managedToolBarTB
		managedToolBarTB = new ManagedToolBarController("managedToolBar", coreController, this);
		// Creates control for ActionController refreshEntityActionACT
		refreshEntityActionACT = new ActionController("refreshEntityAction", managedToolBarTB, this) {
			@Override
			public void initialize() {
				getParamMap().put("CONTROLLER", context.getParam("CONTROLLER"));
				super.initialize();
			}
			@Override
			public void createControl() {
				if (isValid()) {
					action = new RefreshEntityAction();
					action.setActionController(this);
				}
				super.createControl();
			}
		};
		// Creates control for ActionController deleteEntityAndCloseActionACT
		deleteEntityAndCloseActionACT = new ActionController("deleteEntityAndCloseAction", managedToolBarTB, this) {
			@Override
			public void initialize() {
				getParamMap().put("CONTROLLER", context.getParam("CONTROLLER"));
				getParamMap().put("TOOL_BAR_TYPE", context.getParam("TOOL_BAR_TYPE"));
				BooleanSupplier evaluatorVALID;
				evaluatorVALID = new BooleanSupplier() {
					public boolean getAsBoolean() {
						return "DETAIL".equals(((String) context.getParam("TOOL_BAR_TYPE")));
					}
				};
				addAccessibility(new ElementaryAccessibility(ElementaryAccessibility.ACCESS_ATTRIBUTE.VALID, evaluatorVALID));
				super.initialize();
			}
			@Override
			public void createControl() {
				if (isValid()) {
					action = new DeleteEntityAndCloseAction();
					action.setActionController(this);
				}
				super.createControl();
			}
		};
		// Creates control for ActionController deleteEntityActionACT
		deleteEntityActionACT = new ActionController("deleteEntityAction", managedToolBarTB, this) {
			@Override
			public void initialize() {
				getParamMap().put("CONTROLLER", context.getParam("CONTROLLER"));
				getParamMap().put("TOOL_BAR_TYPE", context.getParam("TOOL_BAR_TYPE"));
				BooleanSupplier evaluatorVALID;
				evaluatorVALID = new BooleanSupplier() {
					public boolean getAsBoolean() {
						return genCode.checkPrivilege(IEntityConstants.REMOVE) && "CHILD".equals(((String) context.getParam("TOOL_BAR_TYPE")));
					}
				};
				addAccessibility(new ElementaryAccessibility(ElementaryAccessibility.ACCESS_ATTRIBUTE.VALID, evaluatorVALID));
				super.initialize();
			}
			@Override
			public void createControl() {
				if (isValid()) {
					action = new DeleteEntityAction();
					action.setActionController(this);
				}
				super.createControl();
			}
		};
	}
}