/**********************************************************************************************
 * This class was automatically generated by Adichatz tools on Tue Jul 07 12:30:03 CEST 2020
 *
 * 				+----------------------------------------+
 * 				| BE CAREFUL BEFORE UPDATING THIS CLASS! |
 * 				+----------------------------------------+
 *
 * Changes will be transient up to next generation process.
 * **********************************************************************************************/
package org.adichatz.jpa.gencode.common.toolBar;

import org.adichatz.engine.controller.IContainerController;
import org.adichatz.engine.controller.action.ActionController;
import org.adichatz.engine.controller.collection.ManagedToolBarController;
import org.adichatz.engine.core.AIncludeCore;
import org.adichatz.engine.extra.AdiResourceURI;
import org.adichatz.engine.plugin.AdiContext;
import org.adichatz.engine.plugin.ParamMap;
import org.adichatz.jpa.action.AddOTOEntityAction;
import org.adichatz.jpa.action.DeleteOTOEntityAction;
import org.adichatz.jpa.action.RefreshOTOEntityAction;

@AdiResourceURI(URI="adi://org.adichatz.jpa/common.toolBar/SectionOneToOneDetailTBM")
public class SectionOneToOneDetailTBM extends AIncludeCore {
	// the ManagedToolBarController managedToolBarTB.
	protected ManagedToolBarController managedToolBarTB;
	// the ActionController refreshOTOEntityActionACT.
	private ActionController refreshOTOEntityActionACT;
	// the ActionController addOTOEntityActionACT.
	private ActionController addOTOEntityActionACT;
	// the ActionController deleteOTOEntityActionACT.
	private ActionController deleteOTOEntityActionACT;
	/**
	 * Instantiates a new SectionOneToOneDetailTBM.
	 * 
	 * This constructor could be used by Column parameter. (see org.adichatz.jpa)
	 * 
	 * @param parentContext
	 *            the parent context
	 * @param parentController
	 *            the parent controller
	 */
	public SectionOneToOneDetailTBM(AdiContext parentContext, IContainerController parentController) {
		coreController = parentController;
	}

	/**
	 * Creates the include SectionOneToOneDetailTBM.
	 *
	 * @param context
	 *            The context of the root controller
	 * @param parent controller
	 *            The collection parentController
	 * @param id
	 *            The include id
	 * @param parentContext
	 *            The parent context
	 */
	public SectionOneToOneDetailTBM(ParamMap paramMap, IContainerController parentController, String id, AdiContext parentContext) {
		super(paramMap, parentController, id, parentContext);
		coreController = parentController;
	}

	/**
	 * creates contents
	 */
	public void createContents(){
		// Creates control for ManagedToolBarController managedToolBarTB
		managedToolBarTB = new ManagedToolBarController("managedToolBar", coreController, this);
		// Creates control for ActionController refreshOTOEntityActionACT
		refreshOTOEntityActionACT = new ActionController("refreshOTOEntityAction", managedToolBarTB, this) {
			@Override
			public void initialize() {
				getParamMap().put("CONTROLLER", context.getParam("CONTROLLER"));
				super.initialize();
			}
			@Override
			public void createControl() {
				if (isValid()) {
					action = new RefreshOTOEntityAction();
					action.setActionController(this);
				}
				super.createControl();
			}
		};
		// Creates control for ActionController addOTOEntityActionACT
		addOTOEntityActionACT = new ActionController("addOTOEntityAction", managedToolBarTB, this) {
			@Override
			public void initialize() {
				getParamMap().put("CONTROLLER", context.getParam("CONTROLLER"));
				super.initialize();
			}
			@Override
			public void createControl() {
				if (isValid()) {
					action = new AddOTOEntityAction();
					action.setActionController(this);
				}
				super.createControl();
			}
		};
		// Creates control for ActionController deleteOTOEntityActionACT
		deleteOTOEntityActionACT = new ActionController("deleteOTOEntityAction", managedToolBarTB, this) {
			@Override
			public void initialize() {
				getParamMap().put("CONTROLLER", context.getParam("CONTROLLER"));
				super.initialize();
			}
			@Override
			public void createControl() {
				if (isValid()) {
					action = new DeleteOTOEntityAction();
					action.setActionController(this);
				}
				super.createControl();
			}
		};
	}
}