package org.adichatz.generator;

public class AGenerator {
	public enum LIFECYCLE_STAGE {
		AFTER_INSTANTIATE_CONTROLLER, BEFORE_ENTITY_INJECTION, AFTER_ENTITY_INJECTION, PARAM_CREATE_CONTROL, BEFORE_INITIALIZE, AFTER_INITIALIZE, BEFORE_CREATE_CONTROL, AFTER_CREATE_CONTROL, BEFORE_SYNCHRONIZE, AFTER_SYNCHRONIZE, AFTER_START_LIFE_CYCLE, BEFORE_END_LIFE_CYCLE, AFTER_END_LIFE_CYCLE
	};
}
